name: ci-notify
on:
  workflow_run:
    workflows: [ "backend-ci" ]
    types: [ completed ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Telegram (skip if secrets missing)
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          STATUS: ${{ github.event.workflow_run.conclusion }}
          URL: ${{ github.event.workflow_run.html_url }}
          BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: |
          if [ -z "${TELEGRAM_TOKEN}" ] || [ -z "${TELEGRAM_CHAT_ID}" ]; then
            echo "Telegram secrets not configured; skipping notification."
            exit 0
          fi
          msg="CI *${STATUS}* for branch \`${BRANCH}\`\n[Open run](${URL})"
          curl -sS "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d "chat_id=${TELEGRAM_CHAT_ID}" \
            -d "parse_mode=Markdown" \
            --data-urlencode "text=${msg}"
