name: agent-autocommit

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Target branch"
        default: "main"
        required: true
      commit_message:
        description: "Commit message"
        default: "chore(agent): apply automated changes"
        required: true
      workdir:
        description: "Working directory"
        default: "apps/backend"
        required: true
      commands:
        description: "Shell commands to run before commit (one per line)"
        default: |
          npm install --package-lock-only
        required: false

permissions:
  contents: write

jobs:
  apply-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          # ❗без cache и без cache-dependency-path, чтобы не падать, когда нет package-lock.json

      - name: Run agent commands
        run: |
          set -e
          cd "${{ github.event.inputs.workdir }}"
          echo "${{ github.event.inputs.commands }}" | while IFS= read -r cmd; do
            [ -z "$cmd" ] && continue
            echo "→ $cmd"
            bash -lc "$cmd"
          done

      - name: Auto-commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ github.event.inputs.commit_message }}
          branch: ${{ github.event.inputs.branch }}
          commit_user_name: "feedbacker-agent"
          commit_user_email: "agent@users.noreply.github.com"
          commit_options: "--no-verify"
        env:
          GITHUB_TOKEN: ${{ secrets.AGENT_GITHUB_TOKEN }}
