name: backend-ci

on:
  push:
    branches: [ main, feedbacker-ci ]
    paths:
      - "apps/backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    branches: [ main, feedbacker-ci ]
    paths:
      - "apps/backend/**"
      - ".github/workflows/backend-ci.yml"

permissions:
  contents: read

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (for Newman only)
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Newman
        run: npm i -g newman@6 newman-reporter-junitfull@1

      # === DEPLOY TO RENDER ===
      - name: Deploy to Render
        if: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feedbacker-ci') && success() }}
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -sS -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            -d '{}'

      # === WARMUP AFTER DEPLOY ===
      - name: Warm up backend (retry /health)
        env:
          FEEDBACK_API_URL: ${{ secrets.FEEDBACK_API_URL }}
        run: |
          BASE_URL="${FEEDBACK_API_URL:-https://feedbacker3.onrender.com}"
          echo "Warming up $BASE_URL ..."
          for i in $(seq 1 30); do
            code=$(curl -sS -o /dev/null -w "%{http_code}" "$BASE_URL/health" || true)
            echo "Attempt $i -> HTTP $code"
            if [ "$code" = "200" ]; then exit 0; fi
            sleep 5
          done
          echo "Backend is not ready after retries"; exit 1

      # === POSTMAN / NEWMAN SANITY ===
      - name: Postman (Newman) • One-Click sanity
        if: ${{ hashFiles('apps/backend/postman/*.json') != '' }}
        run: |
          BASE_URL="${FEEDBACK_API_URL:-https://feedbacker3.onrender.com}"
          newman run apps/backend/postman/Feedbacker_OneClick_0902.postman_collection.json \
            -e apps/backend/postman/Feedbacker_ENV_0902.postman_environment.json \
            --env-var baseUrl="$BASE_URL" \
            --timeout-request 15000 --timeout 180000 --delay-request 300 \
            -r cli,junitfull \
            --reporter-junitfull-export apps/backend/newman-results.xml
        env:
          FEEDBACK_API_URL: ${{ secrets.FEEDBACK_API_URL }}
          TELEGRAM_ALERT_THRESHOLD: ${{ secrets.TELEGRAM_ALERT_THRESHOLD }}

      - name: Upload Newman JUnit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-results
          path: apps/backend/newman-results.xml

      # Быстрый дымовой вывод для дебага
      - name: Quick debug endpoints
        if: always()
        env:
          FEEDBACK_API_URL: ${{ secrets.FEEDBACK_API_URL }}
        run: |
          BASE_URL="${FEEDBACK_API_URL:-https://feedbacker3.onrender.com}"
          set -x
          curl -i "$BASE_URL/health" || true
          curl -i "$BASE_URL/" || true
